### ISSUE TITLE
* support for multiple stations around multiple planets/moons

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#10]
Already on the list but added as a specific issue for easier reference

**Comment by severedsolo** [comment]
Pushed back to 0.3

**Comment by severedsolo** [comment]
0.3 is going to focus on mod support, so this is now scheduled for 0.4

**Comment by metl** [comment]
I can start working on this if you want. It shouldn't be much more than cloning what is already done for the different bodies.

**Comment by severedsolo** [comment]
Yeah if you want to, I agree the stock missions are ok for Mun/Minmus, I'm a bit unsure about further afield though, but by all means take a look.

**Comment by metl** [comment]
I'll get the core missions set up. Don't want to get too far ahead to avoid having to go back and change a bunch as mod support is added.

**Comment by severedsolo** [comment]
In preparation for 1.0 and multiple bodies I think it may be an idea to move each body into its own folder, this will make it easier for future releases too as I won't need to take all the other files out each time I release. 

I also plan to change the Tier3Station group to KerbinTier3 for future compatibility

**Comment by severedsolo** [comment]
I take another look at this once 1.0 is released

**Comment by metl** [comment]
Sounds like a good idea. I had considered doing each planet group completely in one cfg file, but folders may be a better way for troubleshooting reasons.

**Comment by severedsolo** [comment]
Yeah one cfg would be a nightmare, it's bad enough now if you mess up the parenthesis, I don't need every contract failing lol

**Comment by severedsolo** [comment]
Done, and released with 1.0

**Comment by severedsolo** [comment]
Woops. cloesed wrong issue

**Comment by severedsolo** [comment]
Mun and Minmus added.

**Comment by severedsolo** [comment]
Duna next? Not sure what to do with inteplanetary targets, I think evac and repair missions seem a big... silly at those distances. The problem would be over one way or another by the time you get there.

**Comment by metl** [comment]
Yeah an EVAC mission would be tough. Maybe we could change the modules
around a little and have one that requires adding an EVAC section capable
of at least reaching the surface? The EVAC mission would basically include "undock and land on Duna" or something to that effect.

**Comment by severedsolo** [comment]
Technically speaking, the current EVAC mission just requires you to empty out the station. You don't even have to get them back to Kerbin, it's just literally undock, switch back to station, mission completes.

**Comment by severedsolo** [comment]
I wonder if we could incorporate this into my science idea, maybe a new Tier 2 that requires a service module capable of landing

**Comment by severedsolo** [comment]
Issue closed - further discussion can be left on the main 1.2/2.0 thread
