### ISSUE TITLE
Core Contract appearing before Dock Node Unlocked

### ISSUE THREAD

**Issue by metl** [severedsolo/KerbinSpaceStation#12]
Station Core contract is available before having the docking node unlocked. Can accept contract, no requirements listed for completion.

**Comment by severedsolo** [comment]
Conf'd bug in dev version (release ok), missing a parenthesis at the end. Now fixed, committed to master.

**Comment by severedsolo** [comment]
Just a thought, did you reload the contract through the debug menu? CC doesn't like that

**Comment by severedsolo** [comment]
Also can you confirm you are using the release version? I saw something in your fork that might cause this, for obvious reasons I'm only going to fix release issues (the dev version is often incomplete, I have a young daughter and tend to leave things half finished)

**Comment by severedsolo** [comment]
Bug was introduced in Dev version - as I thought a } was missing. I've fixed it in my master version - leaving issue open for now in case metl wants to add anything.

**Comment by metl** [comment]
For computability reasons with other mods that unlock docking earlier than where the Station Core port is located, it might be best to change the requirement to be the specific part instead of the module.

**Comment by severedsolo** [comment]
Already fixed in the latest RC - I changed my mind about your requirement for specialist construction and put it back in
