### ISSUE TITLE
Remove the Failsafe

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#15]
It's buggy and doesn't work properly, so I'm just going to remove it entirely. 

If the player messes up their station then tough. At a later date I will allow a 2nd station to be built.

**Comment by metl** [comment]
A better way to handle the fail safe may be to have the contract check to see if the proper vessel is in orbit using an expression. I'm messing with it now but I just can't seem to get the language right.

**Comment by severedsolo** [comment]
I think I've managed it, but I think I'm running into a CC bug, as the expression doesn't reset when the vessel is deleted. I've posted to the CC thread, hopefully nightingale can confirm it's a bug.

**Comment by metl** [comment]
I just saw your discussion with Nightingale. That was the same path I had been attempting to follow.

**Comment by severedsolo** [comment]
Failsafe removed - Nightingale is fixing the issue with docking vessels so should be ok. Added a warning note to StationCore contract that they can only have one station.

**Comment by metl** [comment]
I think I figured out how to do it using the DATA node.

**Comment by severedsolo** [comment]
Issue re-opened

**Comment by severedsolo** [comment]
Interesting - but I can't merge your pull request (or rather I don't want to) as you've taken out all my TAC and StationScience support nodes that I've added. If it works though, let me know and I'll try a manual merge.

**Comment by metl** [comment]
Dang it. I reverted mine back just so i could pull yours in and add my stuff to it. Apparently I didn't do it right. I'll fix it tomorrow for you.

**Comment by metl** [comment]
Looks like it is not working now anyway. Not sure if it was the CC update or if I just didn't test it heavily enough the first time. Let's just say I don't get paid for my programming knowledge! LOL!

**Comment by metl** [comment]
The latest commit should have the situation resolved. I sent a pull request.

**Comment by severedsolo** [comment]
Cool, I'll have a look and do the pull tonight

**Comment by severedsolo** [comment]
Closing this one down ad I've removed the old system, continue to track under other issue
