### ISSUE TITLE
Targetvessel about to become deprecated 

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#16]
Need to rewrite data nodes for most of the contracts

**Comment by metl** [comment]
Does the DATA node need added to the core or does it pull from the vessel ID defined in the vessel parameter group? Hopefully this will fix the problem with expressions not recognizing vessel IDs.

**Comment by severedsolo** [comment]
The core uses "define" as we expect that the defined vessel won't exist yet...  so there shouldn't be a target vessel. 

It's totally redundant anyway, most of the contracts check under VesselParameterGroup anyway, I only had it in there to try and fix the expression issue.

Unfortunately I don't think DATA will do what we need it to, as nightingale confirmed that it's working as intended, (ie if it returns no, it never fires). Nightingale is investigating for now, but I'm going to just make it a "tough luck" situation and give the player a warning in the contract notes.

**Comment by severedsolo** [comment]
targetVessel removed from all contracts. Now checked under VesselParameterGroup only.

**Comment by metl** [comment]
I saw the wiki on DATA nodes had something I didn't notice before, so I am going to try this:

DATA
    {
        type = Vessel
        requiredValue = false
        targetVessel = LKOStation

According to the wiki now, the required value of either NULL or Not NULL determines whether the contract appears or not. In theory then, a requirement of NULL should keep the core contract from appearing if there is a LKOStation, and the opposite on the expansion modules. I'm working on it now as kind of the last ditch effort. I'll let you know.

**Comment by metl** [comment]
Think I figured it out. Check my latest commit.
