### ISSUE TITLE
Station docking port issue 

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#18]
Report from the forum - station docking port may not be registering a docking event

**Comment by severedsolo** [comment]
Nope works fine... waiting for further info, unable to reproduce.

**Comment by metl** [comment]
I had an issue with this, but thought maybe I did something wrong. What it was doing was not recognizing the part as the needed part. Either way, it's fixed in my stuff and if it's working for you then it should be fine on the next release.

**Comment by severedsolo** [comment]
This was one of the tier 2 missions wasn't working, but I think it was a problem with his save, as it wouldn't even load for me or the defined vessel issue, which should now be fixed (which reminds me - note to self to update requirement to latest CC)
