### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#20]
Opening this up mainly to metl, but anyone can weigh in if you like,

As the pack is now basically complete, would a wiki be a good idea do we think, basically explaining the steps for completing each mission

**Comment by metl** [comment]
Might not be a bad idea at all. Most of them are fairly self-explanatory I think, but it never hurts.

**Comment by severedsolo** [comment]
eh, I decided against the wiki. Too busy at home, people can ask if they need to know. I may add a FAQ if necessary
