### ISSUE TITLE
1.1 Plan

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#21]
List of things I want in 1.1:

New Bodies (mandatory): (should just need to clone Kerbin missions - and create new Contract Groups)
Mun
Minmus
All new bodies should not fire until you have at least orbited said body.

Changes/Fixes (all optional)
Finally get to grips with the changing orbit contracts.
Possibly look into adding support for other Life Support mods besides TAC (if they exist)

**Comment by metl** [comment]
I thought up one other idea for a mission: Repair and restore an abandoned station. I think we could do it using the SpawnVessel behavior.

**Comment by severedsolo** [comment]
That sounds interesting, definitely worth further investigation

**Comment by severedsolo** [comment]
As far as I'm concerned 1.1 is done. Do you want to look into SpawnVessel? Or shall we save that for 1.2?

**Comment by metl** [comment]
Just save it. I've been super busy this week and haven't been able to look
at much.

**Comment by severedsolo** [comment]
Yeah you and me both, ok I'll push a release later tonight if nobody comes back on the RC

**Comment by severedsolo** [comment]
1.1 Released
