### ISSUE TITLE
Possible incompatibility issues with stock revamp 

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#23]
Might be a CC issue, but I noticed stock revamp uses its own mesh, it's possible it's not quite sitting right with the stock clamp-o-tron, might need another mm config to fix

**Comment by metl** [comment]
Yeah probably have to force the mm config to use the stock mbm.

On Tue, Apr 7, 2015 at 1:44 AM, severedsolo notifications@github.com
wrote:

> Might be a CC issue, but I noticed stock revamp uses its own mesh, it's
> possible it's not quite sitting right with the stock clamp-o-tron, might
> need another mm config to fix
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/severedsolo/KerbinSpaceStation/issues/23.

## 

Jacob Kelley
_Chief of Police_
City of Granby
302 N Main St
Granby, MO 64844
(417) 472-3535

**Comment by severedsolo** [comment]
As it turns out, it was an issue with contract configurator, nightingale has fixed it
