### ISSUE TITLE
KerbinScienceExperimentModule Bug

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#24]
So it seems if you are using a strategy to convert all your science into something else (ie funds), the mission won't complete because no science gain is registered.

**Comment by metl** [comment]
Well that's an interesting problem. That would have to be a CC issue.

**Comment by severedsolo** [comment]
I'll look to put a fix in at a later date. The only way around it I can think of is to disable the mission once the tech tree is finished, but I don't like that idea.

**Comment by severedsolo** [comment]
Added a note to the contract to warn players. Will monitor to see how much of a problem it is.
