### ISSUE TITLE
Core Contract reappearance

### ISSUE THREAD

**Issue by metl** [severedsolo/KerbinSpaceStation#25]
It would seem that after the hab module and power module are in place, the core mission comes up again.  It was easily worked around by just switching to the station after accepting the contract, but it reappeared again after completing the lab addition. I am going to remove the Mun files and see if it persists.

**Comment by metl** [comment]
I am going to remove the Mun files and see if it still happens.

**Comment by severedsolo** [comment]
I ran into this too, but seems to be completely random when it happens, unable to reproduce reliably. It's probably CC losing track again.

**Comment by severedsolo** [comment]
Issue closed for now, if we can reproduce reliably (or get a lot of complaints) will re-look into.
