### ISSUE TITLE
Various Balance Issues

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#32]
Contract rewards are probably a bit generous, and deadlines are probably a bit tight right now.

**Comment by jberkman** [comment]
science experiment advance funds are quite imbalanced.

Just got one that pays a 380k advance, but only 47k for completion.

**Comment by severedsolo** [comment]
I'll fix this up tonight, I think I forgot to change the advance when I did the balancing pass

**Comment by severedsolo** [comment]
Fixed in the emergency fix build - full release pending.

**Comment by severedsolo** [comment]
Should all now be fixed once I release 2.1
