### ISSUE TITLE
Support for Near Future Electrical

### ISSUE THREAD

**Issue by fraz86** [severedsolo/KerbinSpaceStation#38]
PARAMETER:NEEDS[NearFutureElectrical]
{
    name = PartValidationNearFutureReactors
    type = PartValidation
    title = 1 or more fission reactors
    hideChildren = true
    partModule = FissionReactor
    minCount = 1
}
PARAMETER:NEEDS[NearFutureElectrical]
{
    name = PartValidationNearFutureRTGs
    type = PartValidation
    title = 1 or more radioisotope generators
    hideChildren = true
    partModule = ModuleRadioisotopeGenerator
    minCount = 1
}

**Comment by severedsolo** [comment]
Added to #39

**Comment by severedsolo** [comment]
I've done this - in future please feel free to raise a Pull Request - as you already did the work.
