### ISSUE TITLE
Crew Rotation contract appears even when no crew is present on the station.

### ISSUE THREAD

**Issue by ghost** [severedsolo/KerbinSpaceStation#40]
The title sums it up.  It just seems a little odd to have to rotate a nonexistant crew.

**Comment by severedsolo** [comment]
In a weird sort of way it's deliberate. I debated having a separate "take a crew up" mission, but decided against it, so we just have one mission to cover all situations.

**Comment by ghost** [comment]
Makes sense, I suppose.  It just felt a bit weird with the requirements for
competition wanting me to "rotate the crew".  You can close this, I guess.

**Comment by severedsolo** [comment]
Reopening this, as it was mentioned on the forums too. Now that I think about it, it doesn't make sense to make the crew module return to Kerbin empty when you send up your first crew.

**Comment by severedsolo** [comment]
Related to, and will be fixed under #43

**Comment by ghost** [comment]
Sounds good.
