### ISSUE TITLE
CKAN mark KerbinSpaceStation and UsefulSpaceStation as conflicting

### ISSUE THREAD

**Issue by jakkarth** [severedsolo/KerbinSpaceStation#41]
I'm not sure if this is the right place to bring this up, but I've been experiencing an issue related to these two mods. I have both of them installed through CKAN. The paths are different and the parameters are different, but the contract names are duplicated, which causes exceptions to be thrown when the game attempts to generate new contracts. If you intend to allow both of them to be installed simultaneously, I believe the contract names in one or the other need to be modified so they don't overlap. If you don't intend for them to be installed simultaneously, they should be marked as conflicting each other in the CKAN metadata so that people can't accidentally install both at once, and that should be spelled out clearly on the forum page (and on the README.md page here on github, which seems to be missing) for those who install it manually rather than through CKAN.

**Comment by severedsolo** [comment]
They are already incompatible on CKAN - but, fair point about making it clearer, I'll fix that in a bit

**Comment by jakkarth** [comment]
Apparently the conflicting part was added sometime after I installed the mods but before I filed this bug report. CKAN is now showing them properly conflicting when it didn't a few days ago. Anyway, thanks!
