### ISSUE TITLE
Extend base contract completes if module already exists

### ISSUE THREAD

**Issue by GarwelGarwel** [severedsolo/KerbinSpaceStation#60]
I've received a contract to extend my surface base by landing a science lab nearby. The base in fact already had one and as soon as I switched to it, the contract was marked as complete.

Perhaps, you should either check that the existing base has no lab or prevent it from triggering or require that a newly launched vessel is required.

**Comment by severedsolo** [comment]
Newly launched vessel is the easiest way to do it, as a "base" may not necessarily be one vessel. Thanks for the report - will fix it up in time for the 1.1 update.

**Comment by severedsolo** [comment]
Fixed for next update
