### ISSUE TITLE
Base self sufficiency patches

### ISSUE THREAD

**Issue by sentania** [severedsolo/KerbinSpaceStation#62]
CONTRACT_TYPE:NEEDS[TACLifeSupport|LifeSupport]  should be changed to CONTRACT_TYPE:NEEDS[TACLifeSupport|USILifeSupport] to properly enable support for USI Life Support.

**Comment by sentania** [comment]
There are a couple of other patches that refernce LifeSupport that should be changed to reference USI - Base Resupply, LSResupply, etc.

**Comment by severedsolo** [comment]
Thanks for the heads up - didn't realise they had changed it. Will put it in the next patch

**Comment by severedsolo** [comment]
And fixed.
