### ISSUE TITLE
CrewRotation too often

### ISSUE THREAD

**Issue by Jaidan** [severedsolo/KerbinSpaceStation#70]
With several stations and bases CrewRotation is a constant stream and seems to come up WAY more often than the 10 day cooldown would imply.  I will probably tweak my own person settings to be closer to 30 or 60 days.  Additionally declining a CrewRotation should reset the cooldown, however it doesn't as it frequently just instantly reappears.  Along that lines I'm not 100% confident the random roll is working as intended since declining the contract end up with a CrewRotation contract instantly replacing it (usually for the same station/base).

**Comment by severedsolo** [comment]
I've extended cooldowns to 30 days.

I can't do anything about declining not activating the cooldown, that's a CC limitation (and I don't really want to anyway).

You are always going to see CrewRotation more than the others as it's got a better chance of generating (which is all the RNG roll does). It may be I need to tweak that, but I think the cooldown changes will help. Release soon.
