### ISSUE TITLE
* add specific science instruments to station

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#8]
Floated by micha - very doable, could even just use the generic science container part for mod support

**Comment by metl** [comment]
What about a requirement to return the science to Kerbin?

**Comment by severedsolo** [comment]
Pushed this back to 0.3

**Comment by metl** [comment]
I have a rough cfg uploaded using CC's science gathering function. At the moment, only the Materials Bay is used. Need to figure out how to get it to pull from a list of available science parts when generating the contract.

**Comment by severedsolo** [comment]
I was thinking maybe just use "Generic Science Container" and let the player decide, but I'm sure CC could manage this using expressions.

**Comment by severedsolo** [comment]
Would this do it do you think?
https://github.com/jrossignol/ContractConfigurator/wiki/Expression-Syntax#lists-of-values

**Comment by metl** [comment]
Tried that, but I may have been doing it wrong.

**Comment by severedsolo** [comment]
Do you still have your prototype cfg? I'm about to start working on this (Mod support is nearly done)

**Comment by metl** [comment]
I uploaded the prototype. I haven't done much work troubleshooting it yet, been a busy few days.

**Comment by metl** [comment]
I found how to allow it to accept ANY science (haven't tested with any mods yet, but I assume it should work.) We can leave it there for now and keep working it down to pull from a random science container if you want.

**Comment by severedsolo** [comment]
At least we have some functionality, I will put together an rc later with your changes and we'll see how it goes, I need to update the pre release anyway as ls has no requirements

**Comment by severedsolo** [comment]
Done and released in 1.0
