### ISSUE TITLE
* change station orbit - may want to overfly different territory, or perform experiments at different altitudes.

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KerbinSpaceStation#9]
Floated by micha, I like this idea but am worried about the inherent wobbliness of docking ports, further testing needed (maybe a pull system?)

**Comment by severedsolo** [comment]
pushed into test branch, so I don't fudge anything up. Need to establish what actually happens when the failsafe kicks in first.

**Comment by metl** [comment]
I'll do some playing around with this.

**Comment by severedsolo** [comment]
The failsafe is bieng removed, it's buggy and doesn't work properly anyway, so go ahead.

**Comment by metl** [comment]
I'm hitting a wall. I am attempting to incorporate the orbit generator into the launch of the core to figure out how it works. I can set a fixed orbit, and I can use the random orbits, but they go all over the place. I am trying to use SMA = Random (740000, 840000) but it simply will not accept the random function.

**Comment by severedsolo** [comment]
Potentially flagged for 1.1 - we'll see.

**Comment by metl** [comment]
Yeah I've not been able to get it to allow a number range. The default orbit generator makes some crazy wild orbit changes.

**Comment by severedsolo** [comment]
So it's been over a year... I don't think I'm going to do this. Dropped.
